/**
 * Instructions:
 * Write a function sumAsync() that accepts two (number) arguments and a callback as third (the callback follows error-first pattern). It calculates the sum asyncronously and passes the result to the callback
 * In case any of the first two arguments is not a number, it calls callback right away, passing an error object.
 * 
 * A function defined like above is NOT a "pure" asynchronous function - in case of error it follows synchronous execution! This is not a good idea as there is no guarantees on order of code execution for all cases.
 * 
 * To test this, call sumAsync() with numbers and then again with non-numbers in the pace indicated - check the order of the logs
 */
function sumAsync( a, b, callback ) {

}

/**
 * Call sumAsync first with numbers, then change to non-numbers
 */




 
console.log( 'end of script' );